module.exports = {
    ID: 'ID:',
    IDS: 'IDS',

    TMP: 'TMP:',
    LOC: 'LOC:',

    FILTER_FREE_DELIVERY: 'FILTER_FREE_DELIVERY',
    FILTER_TOP_500: 'FILTER_TOP_500',
    FILTER_CUISINE: 'FILTER_CUISINE:',

    WEIGHT_REVIEWS: 'WEIGHT_REVIEWS:',
    WEIGHT_DISTANCE: 'WEIGHT_DISTANCE:',
    WEIGHT_NAME: 'WEIGHT_NAME:',
}
