module.exports = {
    ID: 'ID:',
    IDS: 'IDS',

    FILTER_FREE_DELIVERY: 'FILTER_FREE_DELIVERY',
    FILTER_TOP_500: 'FILTER_TOP_500',
    FILTER_COUSINE: 'FILTER_COUSINE:',

    WEIGHT_REVIEWS: 'WEIGHT_REVIEWS:',
    WEIGHT_DISTANCE: 'WEIGHT_DISTANCE:',
    WEIGHT_NAME: 'WEIGHT_NAME:',
} 