module.exports = {
    IDS: 'IDS',

    FILTER_FREE_DELIVERY: 'FILTER_FREE_DELIVERY',
    FILTER_TOP_500: 'FILTER_TOP_500',
    FILTER_COUSINE: 'FILTER_COUSINE_',

    WEIGHT_REVIEWS: 'WEIGHT_REVIEWS_',
    WEIGHT_DISTANCE: 'WEIGHT_DISTANCE_',
    WEIGHT_NAME: 'WEIGHT_NAME_',
} 